version: '3.9'

networks:
  wordpress:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./../wordpress:/var/www/html
    depends_on:
      - php
      - mysql
      - smtp_vivestia
    networks:
      - wordpress

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: P@ssw0rd!
      MYSQL_ROOT_PASSWORD: P@ssw0rd!
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wordpress

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9004:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_VERBOSE=mysql
      - PMA_PORT=3306
      - PMA_USER=wp
      - PMA_PASSWORD=P@ssw0rd!
    networks:
      - wordpress

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - ./../wordpress:/var/www/html
    networks:
      - wordpress

  smtp_vivestia:
    image: rnwood/smtp4dev:latest
    container_name: smtp_vivestia
    restart: always
    ports:
      - 9002:80
      - 2525:25
    networks:
      - wordpress

  wp:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: wp
    entrypoint: ['wp', '--allow-root']
    volumes:
      - ./../wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: P@ssw0rd!
      WORDPRESS_DB_NAME: wp
    networks:
      - wordpress